# Generated by Django 5.2.8 on 2025-11-13 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(choices=[('kazakh', 'Kazakh'), ('russian', 'Russian'), ('english', 'English'), ('spanish', 'Spanish')], help_text='Language the user wants to learn', max_length=20)),
                ('native_language', models.CharField(choices=[('kazakh', 'Kazakh'), ('russian', 'Russian'), ('english', 'English'), ('spanish', 'Spanish')], default='english', help_text="User's native/primary language", max_length=20)),
                ('current_cefr_level', models.CharField(choices=[('A0', 'A0 - Beginner'), ('A1', 'A1 - Elementary'), ('A2', 'A2 - Pre-Intermediate'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A0', help_text='Current CEFR proficiency level', max_length=2)),
                ('learning_preferences', models.JSONField(blank=True, default=dict, help_text='User learning preferences (study time, goals, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
