# Generated by Django 5.2.8 on 2025-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='target_language',
            field=models.CharField(blank=True, choices=[('kazakh', 'Kazakh'), ('russian', 'Russian'), ('english', 'English'), ('spanish', 'Spanish')], help_text='Language the user wants to learn', max_length=20, null=True),
        ),
    ]
