# Generated by Django 5.2.8 on 2026-05-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_target_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='👤', help_text="User's chosen emoji avatar", max_length=5),
        ),
    ]
