# Generated by Django 5.2.8 on 2025-11-13 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kazakh', 'Kazakh'), ('russian', 'Russian'), ('english', 'English'), ('spanish', 'Spanish')], help_text='Target language for this test', max_length=20)),
                ('total_items', models.IntegerField(default=12, help_text='Total number of questions in the test (10-12)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement Test',
                'verbose_name_plural': 'Placement Tests',
                'ordering': ['-created_at'],
                'unique_together': {('language', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='PlacementTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Total score achieved', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible score', max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Score percentage', max_digits=5)),
                ('estimated_cefr_level', models.CharField(choices=[('A0', 'A0 - Beginner'), ('A1', 'A1 - Elementary'), ('A2', 'A2 - Pre-Intermediate'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], help_text='Estimated CEFR level based on test results', max_length=2)),
                ('answers', models.JSONField(help_text="User's answers (JSON object mapping question_id to answer)")),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='learning.placementtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Test Result',
                'verbose_name_plural': 'Placement Test Results',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('cloze', 'Fill in the Blank'), ('translation', 'Translation')], help_text='Type of question', max_length=20)),
                ('question_text', models.JSONField(help_text='Question text (supports multilingual content)')),
                ('correct_answer', models.CharField(help_text='The correct answer', max_length=500)),
                ('options', models.JSONField(blank=True, help_text='Answer options for multiple choice (JSON array)', null=True)),
                ('difficulty_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight for scoring (0.5 = easy, 1.0 = medium, 1.5 = hard)', max_digits=3)),
                ('order', models.IntegerField(default=0, help_text='Display order in the test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.placementtest')),
            ],
            options={
                'verbose_name': 'Placement Test Item',
                'verbose_name_plural': 'Placement Test Items',
                'ordering': ['test', 'order'],
                'unique_together': {('test', 'order')},
            },
        ),
    ]
