# Generated by Django 5.2.8 on 2025-11-13 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kazakh', 'Kazakh'), ('russian', 'Russian'), ('english', 'English'), ('spanish', 'Spanish')], help_text='Target language for this roadmap', max_length=20)),
                ('cefr_level', models.CharField(choices=[('A0', 'A0 - Beginner'), ('A1', 'A1 - Elementary'), ('A2', 'A2 - Pre-Intermediate'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], help_text='CEFR level this roadmap is designed for', max_length=2)),
                ('generated_by_ai', models.BooleanField(default=True, help_text='Whether this roadmap was AI-generated or manually created')),
                ('roadmap_data', models.JSONField(blank=True, help_text='Full roadmap structure as JSON (backup)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Whether this is the user's current active roadmap")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roadmap',
                'verbose_name_plural': 'Roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Module title', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the module')),
                ('objectives', models.JSONField(default=list, help_text='Learning objectives (array of strings)')),
                ('order', models.IntegerField(default=0, help_text='Display order in the roadmap')),
                ('checkpoint_criteria', models.JSONField(default=dict, help_text='Criteria for completing this module (e.g., min accuracy, tasks)')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the user has completed this module')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the module was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.roadmap')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['roadmap', 'order'],
                'unique_together': {('roadmap', 'order')},
            },
        ),
    ]
