# Generated by Django 5.2.8 on 2025-11-13 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_roadmap_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of this task instance', max_length=20)),
                ('attempts_count', models.IntegerField(default=0, help_text='Number of attempts made')),
                ('best_attempt_correct', models.BooleanField(default=False, help_text='Whether the best attempt was correct')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Instance',
                'verbose_name_plural': 'Task Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(help_text="User's submitted answer", max_length=1000)),
                ('is_correct', models.BooleanField(help_text='Whether the answer was correct')),
                ('feedback', models.JSONField(default=dict, help_text='Feedback provided (rule, contrast, tip, etc.)')),
                ('xp_gained', models.IntegerField(default=0, help_text='XP points earned from this attempt')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('task_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.taskinstance')),
            ],
            options={
                'verbose_name': 'Task Attempt',
                'verbose_name_plural': 'Task Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('translation', 'Translation')], help_text='Type of task', max_length=20)),
                ('content', models.JSONField(help_text='Task content (question, options, context, etc.)')),
                ('correct_answer', models.CharField(help_text='The correct answer', max_length=500)),
                ('rule_explanation', models.TextField(blank=True, help_text='Grammar/vocabulary rule explanation')),
                ('example_contrast', models.TextField(blank=True, help_text='Example showing correct vs incorrect usage')),
                ('difficulty_level', models.IntegerField(default=1, help_text='Difficulty level (1=easy, 2=medium, 3=hard)')),
                ('created_by_ai', models.BooleanField(default=False, help_text='Whether this task was AI-generated')),
                ('order', models.IntegerField(default=0, help_text='Display order within the module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.module')),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='learning.tasktemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='taskinstance',
            unique_together={('user', 'template')},
        ),
    ]
