# Generated by Django 5.2.8 on 2025-11-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_taskinstance_taskattempt_tasktemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Scenario title (e.g., 'At a Café')", max_length=200)),
                ('language', models.CharField(choices=[('kazakh', 'Kazakh'), ('russian', 'Russian'), ('english', 'English'), ('spanish', 'Spanish')], help_text='Target language for this scenario', max_length=20)),
                ('cefr_level', models.CharField(choices=[('A0', 'A0 - Beginner'), ('A1', 'A1 - Elementary'), ('A2', 'A2 - Pre-Intermediate'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], help_text='Recommended CEFR level', max_length=2)),
                ('context_description', models.TextField(help_text='Description of the scenario context')),
                ('max_turns', models.IntegerField(default=10, help_text='Maximum number of conversation turns')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scenario is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dialogue Scenario',
                'verbose_name_plural': 'Dialogue Scenarios',
                'ordering': ['language', 'cefr_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DialogueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', help_text='Current status of the session', max_length=20)),
                ('turn_count', models.IntegerField(default=0, help_text='Number of turns completed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the session ended', null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.dialoguescenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dialogue Session',
                'verbose_name_plural': 'Dialogue Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DialogueTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(help_text='Turn number in sequence')),
                ('user_message', models.TextField(help_text='Message sent by the user')),
                ('ai_response', models.TextField(help_text='AI-generated response')),
                ('corrections', models.JSONField(default=list, help_text='Inline corrections (array of correction objects)')),
                ('reformulation', models.TextField(blank=True, help_text="Reformulated/corrected version of user's message")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='learning.dialoguesession')),
            ],
            options={
                'verbose_name': 'Dialogue Turn',
                'verbose_name_plural': 'Dialogue Turns',
                'ordering': ['session', 'turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
