# Generated by Django 5.2.8 on 2025-11-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_dialoguescenario_dialoguesession_dialogueturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, help_text='Total experience points earned')),
                ('current_streak_days', models.IntegerField(default=0, help_text='Current consecutive days of activity')),
                ('longest_streak_days', models.IntegerField(default=0, help_text='Longest streak ever achieved')),
                ('last_activity_date', models.DateField(blank=True, help_text='Last date user had activity', null=True)),
                ('xp_history', models.JSONField(default=dict, help_text='History of XP earned per day (date: xp_amount)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamification Profile',
                'verbose_name_plural': 'Gamification Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_attempted', models.IntegerField(default=0, help_text='Number of tasks attempted in this module')),
                ('tasks_completed', models.IntegerField(default=0, help_text='Number of tasks completed successfully')),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall accuracy percentage for this module', max_digits=5)),
                ('last_activity_date', models.DateField(blank=True, help_text='Last date user worked on this module', null=True)),
                ('snapshot_date', models.DateField(auto_now=True, help_text='Date of this snapshot')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Snapshot',
                'verbose_name_plural': 'Progress Snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
